version: '3.8'

services:
  # Node.js 
  app:
    build: ./app
    ports:
      - "10000:10000"
    depends_on:
      - fluentd

  # Fluentd 
  fluentd:
    image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch7-1
    user: root
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluent.conf
    depends_on:
      - elasticsearch

  # Elasticsearch 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  # Kibana 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch